name: Python application test with coverage

on: [push, pull_request]

jobs:
  build:   # Must be named 'build' for Scaler test case 4 to pass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest --cov=script --cov-report=term-missing

